import os
import sys
from abc import ABC, abstractmethod
from tenacity import retry, stop_after_attempt, wait_exponential
from dotenv import load_dotenv
from groq import Groq

load_dotenv(override=True)

# Abstract base class for modular LLM providers
class LLMProvider(ABC):
    @abstractmethod
    def generate_stream(self, system_prompt: str, user_prompt: str):
        """Yields text tokens as they are generated by the LLM."""
        pass

# Groq implementation of LLMProvider
class GroqProvider(LLMProvider):
    def __init__(self, model_name: str = "openai/gpt-oss-20b"):
        self.api_key = os.getenv("GROQ_API_KEY")
        if not self.api_key:
            print("Warning: GROQ_API_KEY environment variable not found. Please set it in your .env file.", file=sys.stderr)
        self.client = Groq(api_key=self.api_key)
        self.model_name = model_name

    # Tenacity retry logic to handle Groq API rate limits (HTTP 429) or connection hiccups
    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10),
        reraise=True
    )
    def generate_stream(self, system_prompt: str, user_prompt: str):
        stream = self.client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            model=self.model_name,
            temperature=0.0,  # Zero temperature for deterministic grounding
            stream=True
        )
        for chunk in stream:
            content = chunk.choices[0].delta.content
            if content:
                yield content
